### ISSUE TITLE
Adding more supported types

### ISSUE THREAD

**Issue by jbhoosreddy** [nolanlawson/promise-worker#13]
I read the discussion in #1 and I fully agree keeping a simple api for developers.
For my purposes, I converted `Blob` to a Data URI string and passed it back.

But looking on the internet I found libraries which are similar to `JSON.stringify` and `JSON.parse` but they now support "stringifying" a whole range of complex objects.

I was wondering if we could discuss about it and maybe you could tell me the reasons why they would not be useful, if that is the case.

I could submit a PR if it is not such a bad idea and we could see how that works.

**Comment by nolanlawson** [comment]
It's actually more efficient to directly pass Blobs as transferables rather than stringifying them.

However, I've decided I'm not interested in adding a lot of bells and whistles to promise-worker. I like keeping it simple instead. If you need support for base64/blobs/etc. then I encourage you to fork it to write your own; the code is very accessible! 😃

**Comment by nolanlawson** [comment]
Also sorry if this sounds like shutting you down; I think it's a great idea and I encourage you to do it; it's just really hard to maintain larger OSS projects, so I am (selfishly) making my own life easier by keeping the scope of this project small.

**Comment by jbhoosreddy** [comment]
It's alright.. thanks for the tip though.

**Comment by viskin** [comment]
Ok, I needed to move imageData blobs to and from web workers. So I forked the promise-worker library to [promise-worker-transferable](https://github.com/terikon/promise-worker-transferable).

Usage exactly as it's papa lib, with following possibility:

```js
promiseWorker.postMessage(pingImageData, [pingImageData]) // pongImageData transferred from main to worker
.then(function (response) {
  // handle response
}).catch(function (error) {
  // handle error
});
```

and vice versa:

```js
registerPromiseWorker(function (message, withTransferList) {
  return withTransferList(pongImageData, [pongImageData]); // pongImageData transferred from worker to main 
});
```

@jbhoosreddy, please use it if it helpful for you.

**Comment by nolanlawson** [comment]
That’s a great solution. :) I’m happy to add a PR to the README to recommend folks look at promise-worker-transferable if that’s okay with you.

**Comment by viskin** [comment]
Thanks!
Of course, everybody is invited to use and improve 👍

**Comment by jwmann** [comment]
@viskin I'm using your promise-worker-transferrable library to pass blobs back to my app.
This works great on every browser except for IE, even IE11.

I'm getting a `Unhandled promise rejection DataCloneError`
I'm not sure if it's because I'm transferring a blob in IE or if the promise web worker needs a shim or something.

**Comment by jwmann** [comment]
This likely due to the fact that IE doesn't support transferable objects but it technically can support Blobs without that feature. I ended up using `webworker-promise` with `babel-polyfill`
