### ISSUE TITLE
Make `registerPromiseWorker` return a mock worker instance?

### ISSUE THREAD

**Issue by arbesfeld** [nolanlawson/promise-worker#16]
I'm trying to test an app that uses a worker in a node environment, and would like to have a mechanism here to test the worker.

**Comment by nolanlawson** [comment]
I use pseudo-worker with an ajax shim in order to test this in Node. There are probably also lots of Node-based web worker implementations but I haven't looked into them. https://github.com/nolanlawson/promise-worker/blob/3eaf434d0d9c568f8c73df5f87aadc527e829863/test/test.js#L3-L6 https://github.com/nolanlawson/promise-worker/blob/3eaf434d0d9c568f8c73df5f87aadc527e829863/test/xhr-shim.js

Hope this helps!
