### ISSUE TITLE
Don't include Promise polyfill in library

### ISSUE THREAD

**Issue by dariocravero** [nolanlawson/promise-worker#17]
Hi @nolanlawson, I hope you're well :). I was wondering if you'd consider a PR removing `lie` and asking library authors to polyfill `Promise` instead if they still want to support older browsers and inlining `is-promise` to reduce the overhead caused by browserify when bundling it? Thanks, Darío

**Comment by nolanlawson** [comment]
Hey sorry, but I'm kind of loath to offer this kind of option for every library I use that exposes Promises... currently you can remove lie very trivially by doing e.g.:

```
browserify -r promise-worker -x lie
```

However this was discussed recently in a generic way (https://github.com/w3ctag/polyfills/issues/6) and so I have hopes that at some point bundlers like webpack and browserify may offer ageneric solution to this problem.

As for is-promise, yeah I would accept a PR inlining it because it's silly to have a single dependency in the worker file. :)

**Comment by dariocravero** [comment]
Thanks for the link, that's an amazing conversation there ;). Will get to this sometime next week and do that little PR too. I'll leave this open as a reminder for myself mainly if that's alright. Thanks :)
