### ISSUE TITLE
Install fails with webpack 4.. à priori

### ISSUE THREAD

**Issue by jgorene** [nolanlawson/promise-worker#30]
First, thank you for this "small and performant library", that's exactly it!
I use it recently via cdn and it works perfectly...

By cons, I try to use it with webpack 4 without success for the moment.
Would anyone here have been able to install this module with webpack 4?

In this case an example would be welcome because I may have missed something...
Thank you in advance ;)

**Comment by nolanlawson** [comment]
Thanks for opening this issue! What do you mean by "doesn't work"? I think maybe with Webpack, you will need to be clever in how you set things up, because this project has both an in-worker component and an out-worker component.

So you will need to tell Webpack to build one version for the main thread, and another version for the web worker. Then you will `require()` the main script in the main thread, and the "register" script in the other thread. Hope that helps!

**Comment by nolanlawson** [comment]
Just to convince myself that this works with Webpack 4, I wrote a simple "hello world" using Webpack 4 and promise worker. I tried it out and it works. :) https://gist.github.com/nolanlawson/a65d848bd4fc2a7a86bc08739b78f463

Just open up the dev console and you'll see that it is successfully communicating between the main thread and the worker. Closing this issue; please reopen if this doesn't help solve the issue!

**Comment by jgorene** [comment]
@nolanlawson  
Thank you very much and even more for the example :heart:
I hadn't thought of doing it like that indeed, but it makes sense.
Webpack is really useful in the end but I still have a lot to learn about it indeed, no problem.
I haven't been able to test this yet but I will do it as soon as possible, thanks again !
